Changed installation script and modified script for update console environment, added nginx upstream configuration for PHP FPM

diff --git a/environment b/environment
--- a/environment
+++ b/environment
@@ -87,3 +87,40 @@ function check_php_extension() {
   fi;
 }
 
+function create_symlink_to() {
+  SYMLINK_NAME=$1
+  SYMLINK_FROM=$2
+  SYMLINK_TO=$3
+  SYMLINK=$SYMLINK_FROM/$SYMLINK_NAME
+
+  echo " "
+  echo "Trying to create symlink '$SYMLINK' in $SYMLINK_TO";
+  echo "-----"
+
+  if [ -e $SYMLINK ] ; then
+    if [ -d $SYMLINK_TO ] ; then
+      echo -n " Trying to change current directory to: '$SYMLINK_TO' ... "
+      cd $SYMLINK_TO || echo "[ Error ]" && echo "[ OK ]"
+
+      if [ "$(pwd)" = "$SYMLINK_TO" ] ; then
+        if [ -e $SYMLINK_NAME ] ; then
+          echo -n " Trying to delete '$SYMLINK_NAME' ... "
+          sudo rm $SYMLINK_NAME || echo "[ Error ]" && echo "[ OK ]"
+        fi
+
+        echo -n " Trying to create symlink to: '$SYMLINK' ... "
+        sudo ln -s $SYMLINK || echo "[ Error ]" && echo "[ OK ]"
+      else
+        echo  " [ Error ] Can't change current directory to: '$SYMLINK_TO'"
+      fi
+
+    else
+      echo  " [ Error ] Can't find directory: '$SYMLINK_TO'"
+    fi
+  else
+    echo  " [ Error ] '$SYMLINK' doesn't exist"
+  fi
+
+  echo " "
+}
+
